import { db } from "@/lib/db/client";
import { chats, messages } from "@/lib/db/schema";
import { chatWorkflow } from "@/workflows/chat";
import { eq } from "drizzle-orm";
import { start } from "workflow/api";
import { v7 as uuidv7 } from "uuid";
import { createAgentUIStreamResponse, createUIMessageStreamResponse } from "ai";
import { chatAgent, ChatAgentUIMessage } from "@/lib/agent-chat/agent";
import { convertDbMessagesToUIMessages, persistMessages } from "@/lib/agent-chat/utils";
import { config } from "@/lib/config";
import { assert } from "console";
import { getChatMessages } from "@/lib/db/queries";

export function errorHandler(error: unknown) {
  console.error("Error in chat agent", error);
  if (error == null) {
    return "unknown error";
  }

  if (typeof error === "string") {
    return error;
  }

  if (error instanceof Error) {
    return error.message;
  }

  return JSON.stringify(error);
}

export async function POST(request: Request) {
  const { chatId, message } = (await request.json()) as {
    chatId: string;
    message: ChatAgentUIMessage;
  };

  if (!chatId || !message) {
    return new Response("Missing chatId or message", { status: 400 });
  }

  const chat = await db.query.chats.findFirst({
    where: eq(chats.id, chatId),
  });
  if (!chat) {
    return new Response("Chat not found", { status: 404 });
  }

  await persistMessages({
    chatId,
    runId: null,
    messages: [message],
  });

  if(!config.flags.enableWorkflowChat) {
    const history = await getChatMessages(chatId);
    const uiMessages = convertDbMessagesToUIMessages(history);
    return createAgentUIStreamResponse({
      agent: chatAgent,
      messages: uiMessages,
      onFinish: async ({ messages }) => {
        assert(messages.length === 1, "Expected 1 message");
        // persist the messages generated by the agent
        await persistMessages({
          chatId,
          messages: messages as ChatAgentUIMessage[],
        });
      },
      onError: errorHandler,
    });
  }

  const assistantMessageId = uuidv7();
  const run = await start(chatWorkflow, [
    {
      chatId,
      assistantMessageId,
    },
  ]);

  await db.insert(messages).values({
    id: assistantMessageId,
    chatId,
    role: "assistant",
    runId: run.runId,
  });

  const workflowStream = run.readable;
  return createUIMessageStreamResponse({
    stream: workflowStream,
    headers: {
      "x-workflow-run-id": run.runId,
    },
  });
}
